In [1]:
# Chapter 2 Linear Algebra

In [2]:
import numpy as np

In [3]:
# 2.1 Scalars, Vectors, Matrices and Tensors
from transpose import transpose

X = np.random.rand(2, 2)
print("Before the transpose operation: \n", X)
X_transposed = X.T
print("After the transpose operation: \n", X_transposed)

Before the transpose operation: 
 [[ 0.43253935  0.75599784]
 [ 0.89015832  0.88318879]]
After the transpose operation: 
 [[ 0.43253935  0.89015832]
 [ 0.75599784  0.88318879]]


In [4]:
# 2.2 Multiplying Matrices and Vectors
import multiplication as mu

A = np.array([[1, 10], [3, 5]])
B = np.array([[2, 6], [1, 5]])

AB_matrix_product = mu.matrix_product(A, B)
print("The matrix product of A and B is \n", AB_matrix_product)

AB_elementwise_product = mu.elementwise_product(A, B)
print("The element-wise product of A and B is \n", AB_elementwise_product)

C = np.array([1, 3, 5])
D = np.array([2, 4, 6])
CD_dot_product = mu.dot_product(C, D)
print("The dot product of vectors C and D is \n", CD_dot_product)

The matrix product of A and B is 
 [[12 56]
 [11 43]]
The element-wise product of A and B is 
 [[ 2 60]
 [ 3 25]]
The dot product of vectors C and D is 
 44
