In [1]:
# Chapter 2 Linear Algebra

In [2]:
import numpy as np

In [3]:
# 2.1 Scalars, Vectors, Matrices and Tensors
from transpose import transpose

X = np.random.rand(2, 2)
print("Before the transpose operation: \n", X)
X_transposed = X.T
print("After the transpose operation: \n", X_transposed)

Before the transpose operation: 
 [[ 0.41620655  0.10589406]
 [ 0.8183259   0.84075153]]
After the transpose operation: 
 [[ 0.41620655  0.8183259 ]
 [ 0.10589406  0.84075153]]


In [4]:
# 2.2 Multiplying Matrices and Vectors
from multiplication import matrix_product, elementwise_product, dot_product

A = np.array([[1, 10], [3, 5]])
B = np.array([[2, 6], [1, 5]])

AB_matrix_product = matrix_product(A, B)
print("The matrix product of A and B is \n", AB_matrix_product)

AB_elementwise_product = elementwise_product(A, B)
print("The element-wise product of A and B is \n", AB_elementwise_product)

C = np.array([1, 3, 5])
D = np.array([2, 4, 6])
CD_dot_product = dot_product(C, D)
print("The dot product of vectors C and D is \n", CD_dot_product)

The matrix product of A and B is 
 [[12 56]
 [11 43]]
The element-wise product of A and B is 
 [[ 2 60]
 [ 3 25]]
The dot product of vectors C and D is 
 44


In [5]:
# Matrix multiplication is distributive(not strictly in nunmpy due to numerical limitation).
A = np.random.rand(3, 2)
B = np.random.rand(2, 3)
C = np.random.rand(2, 3)

D = matrix_product(A, B + C)
E = matrix_product(A, B) + matrix_product(A, C)

print("Result of A(B + C): \n")
print(D, "\n")
print("Result of AB + AC: \n")
print(E, "\n")

Result of A(B + C): 

[[ 0.75027568  0.80779823  0.91050606]
 [ 1.31665865  1.15250478  1.72171725]
 [ 1.65883216  1.4648897   2.16314303]] 

Result of AB + AC: 

[[ 0.75027568  0.80779823  0.91050606]
 [ 1.31665865  1.15250478  1.72171725]
 [ 1.65883216  1.4648897   2.16314303]] 



In [6]:
# Matrix multiplication is associative(not strictly in nunmpy due to numerical limitation).
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
C = np.random.rand(2, 2)

D = matrix_product(A, matrix_product(B, C))
E = matrix_product(matrix_product(A, B), C)

print("Result of A(BC): \n")
print(D, "\n")
print("Result of (AB)C: \n")
print(E, "\n")

Result of A(BC): 

[[ 0.16209435  0.11675593]
 [ 0.41646913  0.30001237]] 

Result of (AB)C: 

[[ 0.16209435  0.11675593]
 [ 0.41646913  0.30001237]] 



In [7]:
# Matrix multiplication is not commutative.
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

C = matrix_product(A, B)
D = matrix_product(B, A)

print("Result of AB: \n")
print(C, "\n")
print("Result of BA: \n")
print(D, "\n")

Result of AB: 

[[ 0.3783499   0.455311  ]
 [ 0.91523298  0.86267447]] 

Result of BA: 

[[ 1.05994238  0.53368512]
 [ 0.52888737  0.18108199]] 



In [8]:
# The dot product between two vectors is commutative.
A = np.random.rand(5)
B = np.random.rand(5)

C = dot_product(A, B)
D = dot_product(B, A)

print(C, "\n")
print(D, "\n")
print(C == D)

1.13063982395 

1.13063982395 

True


In [9]:
# Let A be a numpy array of shape(m, n) and B be a numpy array of shape(n, m), then the transpose of the matrix product
# of A and B, i.e. AB, is the product of the transpose of B and the transpose of A (not strictly in nunmpy due to 
# numerical limitation).
A = np.random.rand(3, 2)
B = np.random.rand(2, 3)

C = matrix_product(A, B)

D = transpose(matrix_product(A, B))
E = matrix_product(transpose(B), transpose(A))

print(D, "\n")
print(E, "\n")

[[ 0.67719719  0.13107736  0.3204432 ]
 [ 0.4624964   0.19813514  0.24836535]
 [ 0.60700968  0.19780204  0.30905569]] 

[[ 0.67719719  0.13107736  0.3204432 ]
 [ 0.4624964   0.19813514  0.24836535]
 [ 0.60700968  0.19780204  0.30905569]] 



In [10]:
# Matrix-vector product notation provides a more compact representation for a system of linear equations. This may be
# realized in numpy with np.linalg.solve().
A = np.random.rand(2, 2)
B = np.random.rand(2)

x = np.linalg.solve(A, B)
print(x, "\n")
print(matrix_product(A, x),"\n")
print(B, "\n")

[ 2.64339149 -0.73356658] 

[ 0.38038423  0.79515221] 

[ 0.38038423  0.79515221] 



In [11]:
# 2.3 Identity and Inverse matrices

from identity import identity

A = identity(3)
print(A, "\n")

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] 



In [12]:
from inverse import inverse

A = np.random.rand(2, 2)
B = inverse(A)

print(matrix_product(A, B), "\n")
print(matrix_product(B, A), "\n")

[[  1.00000000e+00   4.85690918e-17]
 [  2.24180298e-15   1.00000000e+00]] 

[[  1.00000000e+00   7.29994468e-16]
 [ -1.19696720e-16   1.00000000e+00]] 



In [13]:
from norm import Lp_norm, max_norm, frobenius_norm

A = np.array([1, -2, 3, -4])

print("The L1 norm of A is: ", Lp_norm(A, 1), "\n")
print("The L2/Euclidean norm of A is: ", Lp_norm(A, 2), "\n")

The L1 norm of A is:  10.0 

The L2/Euclidean norm of A is:  5.47722557505 



In [14]:
print("The max norm of A is: ", max_norm(A), "\n")

The max norm of A is:  4 



In [15]:
A = np.array([1, 2])
B = np.array([[1,2],[3,4]])

print("The Frobenius norm of A is: ", frobenius_norm(A), "\n")
print("The Frobenius norm of B is: ", frobenius_norm(B), "\n")

The Frobenius norm of A is:  2.2360679775 

The Frobenius norm of B is:  5.47722557505 

