In [1]:
# Chapter 2 Linear Algebra

In [2]:
import numpy as np

In [3]:
# 2.1 Scalars, Vectors, Matrices and Tensors
from transpose import transpose

X = np.random.rand(2, 2)
print("Before the transpose operation: \n", X)
X_transposed = X.T
print("After the transpose operation: \n", X_transposed)

Before the transpose operation: 
 [[ 0.55948793  0.86229399]
 [ 0.82821372  0.69653233]]
After the transpose operation: 
 [[ 0.55948793  0.82821372]
 [ 0.86229399  0.69653233]]


In [4]:
# 2.2 Multiplying Matrices and Vectors
from multiplication import matrix_product, elementwise_product, dot_product

A = np.array([[1, 10], [3, 5]])
B = np.array([[2, 6], [1, 5]])

AB_matrix_product = matrix_product(A, B)
print("The matrix product of A and B is \n", AB_matrix_product)

AB_elementwise_product = elementwise_product(A, B)
print("The element-wise product of A and B is \n", AB_elementwise_product)

C = np.array([1, 3, 5])
D = np.array([2, 4, 6])
CD_dot_product = dot_product(C, D)
print("The dot product of vectors C and D is \n", CD_dot_product)

The matrix product of A and B is 
 [[12 56]
 [11 43]]
The element-wise product of A and B is 
 [[ 2 60]
 [ 3 25]]
The dot product of vectors C and D is 
 44


In [5]:
# Matrix multiplication is distributive(not strictly in nunmpy due to numerical limitation).
A = np.random.rand(3, 2)
B = np.random.rand(2, 3)
C = np.random.rand(2, 3)

D = matrix_product(A, B + C)
E = matrix_product(A, B) + matrix_product(A, C)

print("Result of A(B + C): \n")
print(D, "\n")
print("Result of AB + AC: \n")
print(E, "\n")

Result of A(B + C): 

[[ 1.06556983  1.61280966  1.95276262]
 [ 0.42467076  0.81714814  0.80650483]
 [ 0.89072606  1.45310658  1.64934564]] 

Result of AB + AC: 

[[ 1.06556983  1.61280966  1.95276262]
 [ 0.42467076  0.81714814  0.80650483]
 [ 0.89072606  1.45310658  1.64934564]] 



In [6]:
# Matrix multiplication is associative(not strictly in nunmpy due to numerical limitation).
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
C = np.random.rand(2, 2)

D = matrix_product(A, matrix_product(B, C))
E = matrix_product(matrix_product(A, B), C)

print("Result of A(BC): \n")
print(D, "\n")
print("Result of (AB)C: \n")
print(E, "\n")

Result of A(BC): 

[[ 0.85313277  0.57891087]
 [ 1.29057678  0.91708279]] 

Result of (AB)C: 

[[ 0.85313277  0.57891087]
 [ 1.29057678  0.91708279]] 



In [7]:
# Matrix multiplication is not commutative.
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

C = matrix_product(A, B)
D = matrix_product(B, A)

print("Result of AB: \n")
print(C, "\n")
print("Result of BA: \n")
print(D, "\n")

Result of AB: 

[[ 0.54682129  0.53869028]
 [ 0.8679756   0.81307801]] 

Result of BA: 

[[ 0.29972849  0.50995018]
 [ 0.6681536   1.06017082]] 



In [8]:
# The dot product between two vectors is commutative.
A = np.random.rand(5)
B = np.random.rand(5)

C = dot_product(A, B)
D = dot_product(B, A)

print(C, "\n")
print(D, "\n")
print(C == D)

0.984150166546 

0.984150166546 

True


In [9]:
# Let A be a numpy array of shape(m, n) and B be a numpy array of shape(n, m), then the transpose of the matrix product
# of A and B, i.e. AB, is the product of the transpose of B and the transpose of A (not strictly in nunmpy due to 
# numerical limitation).
A = np.random.rand(3, 2)
B = np.random.rand(2, 3)

C = matrix_product(A, B)

D = transpose(matrix_product(A, B))
E = matrix_product(transpose(B), transpose(A))

print(D, "\n")
print(E, "\n")

[[ 0.59721027  0.27793216  0.15032596]
 [ 1.60974214  0.80187513  0.52976534]
 [ 0.62377139  0.3417101   0.27848828]] 

[[ 0.59721027  0.27793216  0.15032596]
 [ 1.60974214  0.80187513  0.52976534]
 [ 0.62377139  0.3417101   0.27848828]] 



In [10]:
# Matrix-vector product notation provides a more compact representation for a system of linear equations. This may be
# realized in numpy with np.linalg.solve().
A = np.random.rand(2, 2)
B = np.random.rand(2)

x = np.linalg.solve(A, B)
print(x, "\n")
print(matrix_product(A, x),"\n")
print(B, "\n")

[-2.65439845  3.50912247] 

[ 0.0923969   0.25654266] 

[ 0.0923969   0.25654266] 



In [11]:
# 2.3 Identity and Inverse matrices

from identity import identity

A = identity(3)
print(A, "\n")

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] 



In [12]:
from inverse import inverse

A = np.random.rand(2, 2)
B = inverse(A)

print(matrix_product(A, B), "\n")
print(matrix_product(B, A), "\n")

[[  1.00000000e+00  -5.79725675e-17]
 [  5.50096610e-17   1.00000000e+00]] 

[[  1.00000000e+00   9.95587511e-18]
 [  1.46077254e-16   1.00000000e+00]] 



In [13]:
# 2.5 Norms

from norm import lp_norm, max_norm, frobenius_norm, angle

A = np.array([1, -2, 3, -4])

print("The L1 norm of A is: ", lp_norm(A, 1), "\n")
print("The L2/Euclidean norm of A is: ", lp_norm(A, 2), "\n")

The L1 norm of A is:  10.0 

The L2/Euclidean norm of A is:  5.47722557505 



In [14]:
print("The max norm of A is: ", max_norm(A), "\n")

The max norm of A is:  4 



In [15]:
A = np.array([1, 2])
B = np.array([[1, 2],[3, 4]])

print("The Frobenius norm of A is: ", frobenius_norm(A), "\n")
print("The Frobenius norm of B is: ", frobenius_norm(B), "\n")

The Frobenius norm of A is:  2.2360679775 

The Frobenius norm of B is:  5.47722557505 



In [16]:
A = np.array([1, 2])
B = np.array([3, 4])

print("The angle between A and B is: ", angle(A, B), "\n")

The angle between A and B is:  0.179853499792 



In [17]:
# 2.6 Special Kinds of Matrices and Vectors

from special_matrices import is_symmetric, is_unit_vector, orthogonal_to_each_other, are_orthonormal, is_orthogonal

A = np.array([[[1,2],[5,6]],[[3,4],[7,8]]])

print("Is A a symmetric matrix?", is_symmetric(A), "\n")

B = np.array([1, 2])

print("Is B a symmetric matrix?", is_symmetric(B), "\n")

C = np.array([[1, 7, 3], [7, 4, -5], [3, -5, 6]])

print("Is C a symmetric matrix?", is_symmetric(C), "\n")

This is not a matrix!
Is A a symmetric matrix? False 

This is a vector, not a matrix!
Is B a symmetric matrix? False 

Is C a symmetric matrix? True 



In [18]:
A = np.array([[1, 0], [0, 0]])

print("Is A a unit vector?", is_unit_vector(A), "\n")

B = np.array([1, 1])

print("Is B a unit vector?", is_unit_vector(B), "\n")

C = np.array([1/2, 1/2, 1/2, 1/2])

print("Is C a unit vector?", is_unit_vector(C), "\n")

This is not a vector!
Is A a unit vector? False 

Is B a unit vector? False 

Is C a unit vector? True 



In [19]:
A = np.array([1, 0])
B = np.array([0, 1])
C = np.array([1, 1])
D = np.array([[1, 2], [3, 4]])

print("Are A and D orthogonal to each other?", orthogonal_to_each_other(A, D), "\n")

print("Are A and C orthogonal to each other?", orthogonal_to_each_other(A, C), "\n")

print("Are A and B orthogonal to each other?", orthogonal_to_each_other(A, B), "\n")

At least one of the numpy array is not a vector!
Are A and D orthogonal to each other? False 

Are A and C orthogonal to each other? False 

Are A and B orthogonal to each other? True 



In [20]:
print("Are A and C orthonormal?", are_orthonormal(A, C), "\n")

print("Are A and B orthonormal?", are_orthonormal(A, B), "\n")

Are A and C orthonormal? False 

Are A and B orthonormal? True 



In [21]:
A = np.array([1])
B = np.array([[1], [2]])
C = np.array([[1, 0], [0, -1]])

print("Is A an orthogonal matrix?", is_orthogonal(A), "\n")

print("Is B an orthogonal matrix?", is_orthogonal(B), "\n")

print("Is C an orthogonal matrix?", is_orthogonal(C), "\n")

This is not a matrix!
Is A an orthogonal matrix? False 

This is not a square matrix!
Is B an orthogonal matrix? False 

Is C an orthogonal matrix? True 

